version: "4.0"

volumes:
  mongo-data:
  postgres-data:
  postgres-adminer-data:
  redis-data:

networks:
  mongo-network:
    driver: bridge
  postgres-network:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb

    networks:
      - mongo-network

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  postgres-admin:
    container_name: postgres-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - postgres-adminer-data:/var/lib/pgadmin
    networks:
      - postgres-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - 5540:5540
    volumes:
      - redis-data:/db
